---
format: 
  pdf: 
    documentclass: article
    geometry:
      - top=1cm
      - left=15mm
      - right=15mm
      - bottom=1cm
      - heightrounded
    fontfamily: libertine
    colorlinks: true
    fontsize: '16'
    include-in-header: 
      text: |
        \usepackage{multicol}
        \usepackage{lipsum}
        \usepackage{hyperref}
        \usepackage{libertine}
        \pagestyle{empty}
        \setlength{\multicolsep}{2pt plus 1.0pt minus 0.75pt}% 50% of original values
        \setlength{\columnsep}{3em}
---
<!-- TITLE -->
\begin{huge}\begin{center}{\bf NAM-ANH TRAN}\end{center}\end{huge}

<!-- CONTACT INFO -->
\begin{center}
nam-anh.tran@mail.mcgill.ca \quad\bullet\quad  +1 647 860 9519
\end{center}

<!-- EDUCATION: 1ST BULLET -->
\begin{large}
  {\bf EDUCATION}
  \vspace{3pt}
  \hrule
  \begin{multicols}{2}
    \begin{flushleft}{\bf McGill University}\end{flushleft}
    \begin{flushright}2023 - \end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}Doctor of Philosophy in Biostatistics\end{flushleft}
  \end{multicols}
  \end{large}

   * \textit{Dissertation Topic:} Statistical methods for design and analysis of adaptive enrichment trials for vaccine development.
   * \textit{Supervisor:} Dr. Shirin Golchi (McGill University)
   *  \textit{Co-supervisor:} Dr. Laura Richert (Université de Bordeaux)
   * \textit{Courses:} Mathematical statistics I \& II, Regression and ANOVA, Advanced Generalized linear models, Bayesian Analysis in the Health Sciences, Advanced Modeling: Survival and Other Multivariable Data, Spatial and Spatio-temporal epidemiology, Machine Learning in Biostatistics. 

\vspace{0.05cm}

<!-- EDUCATION: 2ND BULLET -->
\begin{large}
  \begin{multicols}{2}
    \begin{flushleft}{\bf University of Manitoba}\end{flushleft}
    \begin{flushright}2017 - 2019 \end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}Master of Science in Statistics \end{flushleft}
  \end{multicols}
  \end{large}

   * \textit{Thesis Topic:} Construction of Bayesian Optimal Designs for Nonlinear Models.
   * \textit{Supervisor:} Dr. Saumen Mandal (University of Manitoba)
   * \textit{Courses:} Advanced Statistical Inference, Machine Learning, Linear Models, Non-parametric Inference, Statistical Computing and Sports Analytics, Optimal Designs.

\vspace{0.05cm}

<!-- EDUCATION: 3ND BULLET -->
\begin{large}
  \begin{multicols}{2}
    \begin{flushleft}{\bf University of Manitoba}\end{flushleft}
    \begin{flushright}2012 - 2017 \end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}Bachelor of Science in Statistics \end{flushleft}
  \end{multicols}
\end{large}

\vspace{0.5cm}


<!-- EXPERIENCE : 1ST BULLET-->
\begin{large}{\bf WORK EXPERIENCE}
  \vspace{3pt}
  \hrule
  \begin{multicols}{2}
    \begin{flushleft}{\bf IMPaCT lab (Hospital for Sick Children) }\end{flushleft}
    \begin{flushright}Nov 2021 - Aug 2023 \end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Biostatistical analyst}\end{flushleft}
    \begin{flushright}Toronto, ON, Canada\end{flushright}\end
  {multicols}
\end{large}
* Develop novel statistical methodologies for the prioritization, design and analysis of clinical trials.
* Frame Bayesian adaptive trials for multiple projects in pediatrics, particularly emergency medicine.
* Conduct health-economic models and analyzing Value of Information.
* Write manuscripts and deliver reports. 


<!-- EXPERIENCE : 2ND BULLET -->
\begin{large}
  \begin{multicols}{2}
    \begin{flushleft}{\bf EVERSANA}\end{flushleft}
    \begin{flushright}Nov 2019 - Sep 2021 \end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Biostatistician I}\end
    {flushleft}\begin{flushright}Sydney, NS, Canada\end
    {flushright}
  \end{multicols}
\end{large}
\vspace{-0.16cm}
* Undertake Systematic Reviews for Health Economic Evaluations: 
   * (Network) Meta-analysis.
   * Matching-Adjusted Indirect Comparisons (MAIC).
   * Simulated Treatment Comparisons (STC).
* Conduct MAIC's and STC's for time-to-events data. 
* Deliver reports. 


<!-- EXPERIENCE : 3RD BULLET -->
\begin{large}
  \begin{multicols}{2}
    \begin{flushleft}{\bf University of Manitoba}\end{flushleft}
    \begin{flushright}Sep 2017 - Apr 2018\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Teaching assistant}\end
    {flushleft}\begin{flushright}Winnipeg, MB, Canada \end
    {flushright}
  \end{multicols}
\end{large}

\vspace{0.5cm}

<!-- SKILLS -->
\begin{large}{\bf TECHNICAL SKILLS}
  \vspace{3pt}
  \hrule
\end{large}
\vspace{-0.16cm}
 * \textit{Programming skills:} R, \LaTeX, Git, GitHub.
 
 * \textit{Statistical skills:} Bayesian statistics, adaptive clinical trials, experimental designs, time-to-events analysis, indirect treatment comparisons, health-economic models, statistical learning. 
 
 * \text{Management competencies:} teamwork, time management, independent working skills.

\vspace{0.5cm}

<!-- PROJECTS  -->

\begin{large}{\bf PROJECTS}
  \vspace{3pt}
  \hrule
\end{large}
\vspace{-0.16cm}

* \textbf{Predicting results of hockey game using machine learning methods:} Predicting future hockey game results using neural networks and support vector machines based on historical data extracted from \underline{www.tsn.ca}. Both approaches resulted in an accuracy of more than 60\% (Jan--Mar 2018). \textit{Completed}

* \textbf{A mini project on Artificial Neural Network:} Predicting handwritten digits and images using neural networks. The accuracy of prediction using the neural network was more than $95\%$ (Sep--Dec 2017).  \textit{Completed}

* \textbf{Construction of Optimal Designs for Linear Models:} Reviewing numerical algorithms for constructing the optimal design. Comparing time complexity of multiplicative algorithm against other approaches. The multiplicative algorithm, yielding the continuous optimal design, was more efficient than other approaches to searching the discrete optimal design (May--Aug 2017). \textit{Completed}

\vspace{0.5cm}

<!-- CONFERENCE PRESENTATIONS -->
\begin{large}{\bf CONFERENCE PRESENTATIONS}
  \vspace{3pt}
  \hrule
\end{large}
\vspace{-0.16cm}

* \textbf{Tran, Nam-Anh}, Kent Lu, Mingchi Xu. ``A Suggestion on Prediction of ICU Length of Stay: A Random Forest Approach." \textit{Case Studies in Data Analysis Competition at The Annual Meeting of the Statistical Society of Canada (Saint John, June 2024)}.

* \textbf{Tran, Nam-Anh}, Abigail McGrory, Naveen Poonai, and Anna Heath. ``A Comparison of Alternative Ranking Methods in Two Stage Clinical Trials with Multiple Interventions: An Application to the Anxiolysis for Laceration Repair in Children Trial." \textit{Paper presented at The Seventh Annual (Bio)Statistics Research and Career Day at McGill (Montreal, May 2024)}.

* \textbf{Tran, Nam-Anh}, Naveen Poonai, and Anna Heath. ``A Comparison of Alternative Ranking Methods in Two Stage Clinical Trials with Multiple Interventions: An Application to the Anxiolysis for Laceration Repair in Children Trial." \textit{Paper presented at The Annual Meeting of the Statistical Society of Canada (Ottawa, May 2023)}.

* \textbf{Tran, Nam-Anh}, Anna Heath, Petros Pechlivanoglou, Naveen Poonai, Samina Ali, and Doug Coyle. ``Comparing the costs associated with anxiolytic agents for reducing distress in children undergoing laceration repair in the emergency department." \textit{Paper presented at the Society for Medical Decision Making 44th Annual North American Meeting (Seattle, Oct 2022)}.

* \textbf{Tran, Nam-Anh}, Naveen Poonai, and Anna Heath. ``Selecting the superior treatment in Bayesian two-stage adaptive trial without the common control arm using the SUCRA and the probability of first rank." \textit{Paper presented at Bayesian Biostatistics Conference (Bethesda, Oct 2022)}.

* \textbf{Tran, Nam-Anh}, Saumen Mandal. ``Construction of Bayesian Optimal Designs for Nonlinear Models." \textit{Paper presented at 47th Annual Meeting of the Statistical Society of Canada (Calgary, May 2019)}.

\vspace{0.5cm}


<!-- PUBLICATION -->
\begin{large}{\bf PUBLICATIONS}
  \vspace{3pt}
  \hrule
\end{large}
\vspace{-0.16cm}

* \textbf{Tran, Nam-Anh}, Yi-Shu Lin, Petros Pechlivanoglou, Naveen Poonai, Samina Ali, and Doug Coyle, Anna Heath. ``Comparing the Costs Associated with Anxiolytic Agents for Reducing Distress in Children Undergoing Laceration Repair in the Emergency Department." \textit{Submitted}.

* \textbf{Tran, Nam-Anh}, Abigail McGrory, Naveen Poonai, and Anna Heath. ``A comparison of alternative ranking methods in two-stage clinical trials with multiple interventions: An application to the anxiolysis for laceration repair in children trial." Clinical Trials (2024): 17407745241251812.

* Siu, Annisa, \textbf{Nam-Anh Tran}, Samina Ali, Doug Coyle, Quenby Mahood, Yanara Marks, Petros Pechlivanoglou, Naveen Poonai, and Anna Heath. ``Pharmacologic Procedural Distress Management During Laceration Repair in Children: A Systematic Review." Pediatric Emergency Care 40, no. 2 (2024): 88-97.

* Rugo, Hope S., Anja Haltner, Lin Zhan, \textbf{Anh Tran}, Eustratios Bananis, Becky Hooper, Debanjali Mitra, and Chris Cameron. ``Matching-adjusted indirect comparison of palbociclib versus ribociclib and abemaciclib in hormone receptor-positive/HER2-negative advanced breast cancer." Journal of Comparative Effectiveness Research 10, no. 6 (2021): 457-467.

\vspace{0.5cm}

<!--  ACHIEVEMENTS -->
\begin{large}{\bf ACHIEVEMENTS}
  \vspace{3pt}
  \hrule
\end{large}
\vspace{-0.16cm}

* Graduate Research Enhancement and Travel (GREAT) Awards, $500 (Mar 2024)

* A.Stat. by Statistical Society of Canada (Mar 2021).

* Outstanding Research by a MSc. Student (Feb 2020).

* Outstanding Academic Performance by a MSc. Student (Feb 2019).

* Faculty of Graduate Studies Travel Award, $750 (May 2019).

* Manitoba Graduate Scholarship, $15,000 (Sep 2018).

* International Graduate Student Entrance Scholarship, $5,585 (Sep 2017).

* Summer Undergraduate Research Award, $2,000 (May 2017).


